#version 450

layout(local_size_x = 10, local_size_y = 10, local_size_z = 1) in;


layout(set = 0, binding = 0) buffer restrict writeonly particle_densities{
    int particle_dens[8000];
};

const int fluid_width = 20;
const int fluid_height = 20;
const int fluid_depth = 20;


int getIndex(ivec3 pos){
    return pos.x + (pos.y + pos.z * fluid_height) * fluid_width;
}

const int CELL_WATER = 2;

void main(){
    particle_dens[getIndex(ivec3(gl_GlobalInvocationID.xyz))] = 0;
}