#version 450
#extension GL_EXT_samplerless_texture_functions : require

layout(local_size_x = 256) in;

layout(set = 0, binding = 0, rgba32f) uniform image1D particles;
layout(set = 0, binding = 1) uniform sampler3D velocities;

const float time_delta = 0.01;


void main(){
    int i = gl_GlobalInvocationID.x;
    vec3 pos = imageLoad(particles, int(i)).xyz;
    vec3 v = texture(velocities, pos).xyz;
    imageStore(particles, i, vec4(pos + v*time_delta, 0.0));
}