#version 450

layout(local_size_x = 128, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0, r8ui) uniform restrict writeonly uimage3D cell_types;

const uint CELL_SOLID = 2;

void main(){
    ivec3 i = ivec3(gl_GlobalInvocationID.xyz);
    ivec3 b = imageSize(cell_types) - ivec3(1, 1, 1);
    if ((i.x == 0 || i.x == b.x) && (i.y == 0 || i.y == b.y) && (i.z == 0 || i.z == b.z)){
        imageStore(cell_types, i, uvec4(CELL_SOLID, 0, 0, 0));
    }
}